### PR TITLE
Add .travis.yml configuration

### PR DESCRIPTION
**Pull request by desyncr**

### CODE REVIEW

**Comment by fennecdjay** [comment]
```sh
sudo cp zpm /usr/local/bin/zpm
```
Maybe you missed things like
```sh
  $ zpm list
  zsh-users/zsh-syntax-highlighting .* (re)
  rupa/z .* (re)
```

we need since we display commit hash.

**Comment by fennecdjay** [comment]
could you please use `${PREFIX}` along with `${PREFIX}?=/usr/local` rather than ` /usr/local/`?

**Comment by fennecdjay** [comment]
:tada:

**Comment by fennecdjay** [comment]
Thank You. looks pretty good now. 🍾

**Comment by desyncr** [comment]
I noticed that in travis for zsh-syntax-highlighting plugin it used `.pluging.zsh` file, rather than `.zsh` as it does in local. That's the reason for https://github.com/desyncr/zpm-zsh/pull/28/files#diff-8559167d46adcbf97da96ff0a92a13a2R41

**Comment by fennecdjay** [comment]
Do you think we have to add the wildcard to the formula?

**Comment by desyncr** [comment]
I fixed that using .* (re). We should probably look at the reason it does that. We want to be as deterministic as possible.

**Comment by desyncr** [comment]
Moved PR to https://github.com/zpm-project/zpm-zsh/pull/6

**Pull request closed without merging**
